Clean up repo_cmd_before command for setup-repo
Refactor the mirror setup logic to account for a few issues. We
nolonger hit https://trunk.rdoprojecg.org directly, we use our reverse
proxy.

Add error handling for an empty baseurl, and fail if missing.

Simplify nodepool variables to match /etc/ci/mirror_info.sh.

ALso, why so much copypasta? This is very error prone and should be
moved into a role in a followup patch.

Change-Id: Ia06ebad96c8db2a4eb732e80f04c72ad4c9bc6a3
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

diff --git a/config/release/tripleo-ci/promotion-testing-hash-master.yml b/config/release/tripleo-ci/promotion-testing-hash-master.yml
--- a/config/release/tripleo-ci/promotion-testing-hash-master.yml
+++ b/config/release/tripleo-ci/promotion-testing-hash-master.yml
@@ -25,44 +25,53 @@ release: master
 overcloud_image_url: https://images.rdoproject.org/master/delorean/tripleo-upstream/testing/overcloud-full.tar
 ipa_image_url: https://images.rdoproject.org/master/delorean/tripleo-upstream/testing/ipa_images.tar
 repo_cmd_before: |
-  sudo rm -rf /etc/yum.repos.d/delorean*;
-  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
-  export TESTING_RDO_MIRROR=`curl --silent https://trunk.rdoproject.org/centos7-master/tripleo-ci-testing/delorean.repo | grep baseurl | cut -d= -f2`
-  # If running tripleo-quickstart from review.openstack.org or review.rdoproject.org, try to use AFS mirrors
-  if [[ -e /etc/ci/mirror_info.sh ]]; then
-  eval $(source /etc/ci/mirror_info.sh; echo NODEPOOL_MIRROR_HOST="$NODEPOOL_MIRROR_HOST")
-  export NODEPOOL_MIRROR_HOST="http://${NODEPOOL_MIRROR_HOST}"
-  export TESTING_RDO_MIRROR=${TESTING_RDO_MIRROR/https:\/\/trunk.rdoproject.org/$NODEPOOL_MIRROR_HOST:8080/rdo}
-  fi
-  # Otherwise, fallback to official mirrors provided by CentOS.
-  export NODEPOOL_MIRROR_HOST="${NODEPOOL_MIRROR_HOST:-http://mirror.centos.org}"
   sudo yum install -y yum-plugin-priorities;
   sudo yum clean all;
+  sudo yum-config-manager --disable "*"
+  sudo rm -rf /etc/yum.repos.d/delorean*;
+  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
+  if [ -e /etc/ci/mirror_info.sh ]; then
+    source /etc/ci/mirror_info.sh
+  else
+    # Otherwise, fallback to official mirrors provided by CentOS.
+    export NODEPOOL_CENTOS_MIRROR=http://mirror.centos.org/centos
+    export NODEPOOL_BUILDLOGS_CENTOS_PROXY=https://buildlogs.centos.org
+    export NODEPOOL_RDO_PROXY=http://trunk.rdoproject.org
+  fi
+  rdo_dlrn=`curl --silent ${NODEPOOL_RDO_PROXY}/centos7-master/tripleo-ci-testing/delorean.repo | grep baseurl | cut -d= -f2`
+  rdo_dlrn_deps=`curl --silent ${NODEPOOL_RDO_PROXY}/centos7-master/delorean-deps.repo | grep baseurl | cut -d= -f2`
+  if [[ -z "$rdo_dlrn" || -z "$rdo_dlrn_deps" ]]; then
+    echo "Failed to parse dlrn hash"
+    exit 1
+  fi
+  export RDO_DLRN_REPO=${rdo_dlrn/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
+  export RDO_DLRN_DEPS_REPO=${rdo_dlrn_deps/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
+
 repos:
   - type: generic
     reponame: delorean
     filename: delorean.repo
-    baseurl: $TESTING_RDO_MIRROR
-    hash_url: https://trunk.rdoproject.org/centos7-master/tripleo-ci-testing/delorean.repo
+    baseurl: $RDO_DLRN_REPO
 
-  - type: file
+  - type: generic
+    reponame: delorean-deps
     filename: delorean-deps.repo
-    down_url: https://trunk.rdoproject.org/centos7-master/delorean-deps.repo
+    baseurl: $RDO_DLRN_DEPS_REPO
 
   - type: generic
     reponame: centos-qemu
     filename: centos-qemu.repo
-    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/virt/x86_64/kvm-common/
+    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/virt/x86_64/kvm-common/
 
   - type: generic
     reponame: centos-ceph-jewel
     filename: centos-ceph-jewel.repo
-    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/storage/x86_64/ceph-jewel/
+    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/storage/x86_64/ceph-jewel/
 
   - type: generic
     reponame: centos-opstools
     filename: centos-opstools.repo
-    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/opstools/x86_64/
+    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/opstools/x86_64/
 
 repo_cmd_after: |
   {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt centos-opstools.enable=0;
