Fixes for devmode convert_image
* clean up the file system resize
* propagate errors from the virt-customize script
  to stop the playbook on errors

Change-Id: If174bcd8f40796a7d8031ba158e129b573f036a6

diff --git a/roles/libvirt/setup/undercloud/templates/convert_image.sh.j2 b/roles/libvirt/setup/undercloud/templates/convert_image.sh.j2
--- a/roles/libvirt/setup/undercloud/templates/convert_image.sh.j2
+++ b/roles/libvirt/setup/undercloud/templates/convert_image.sh.j2
@@ -1,5 +1,18 @@
 #!/bin/bash
 
+set -eux
+
+FS_TYPE=`findmnt -o FSTYPE -fn /`
+
+if [ "$FS_TYPE" = "xfs" ]; then
+    xfs_growfs /
+elif [ "$FS_TYPE" = "ext4" ]; then
+    resize2fs /dev/sda
+else
+    echo "ERROR: Unknown filesystem, cannot resize."
+    exit 1
+fi
+
 yum remove -y cloud-init
 yum install -y python-tripleoclient openstack-tempest python-aodh-tests python-ceilometer-tests \
 python-heat-tests python-ironic-tests python-keystone-tests python-manila-tests \
